import { eventTime } from '../shared/event-time.js';
import React, { useEffect, useState } from 'react';
import { api } from './api.js';
import { Tile, parseHand } from './tiles.jsx';
import { YAKU, matchLabel } from '../shared/rules.js';
import { ErrorDetails } from './agent-status.jsx';

function download(name, data) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }));
  const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function Rulebook({ state }) {
  const [tab, setTab] = useState('basics'), [search, setSearch] = useState('');
  return <><div className="modal-heading"><small>RIICHI HANDBOOK</small><h2>日麻规则手册</h2><p>牌桌与手册共用牌面，当前房规以程序配置为准。</p></div><div className="tabs panel-tabs">{[['basics', '基础'], ['actions', '操作'], ['yaku', '役种图鉴'], ['scoring', '计分'], ['current', '当前房规']].map(([id, label]) => <button key={id} className={tab === id ? 'chosen' : ''} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className="handbook-content">{tab === 'basics' && <><h3>摸一张，打一张</h3><p>四人使用 136 张牌，34 种基础牌各四张。万、筒、索各一至九，字牌是东南西北白发中；赤五替换普通五。</p><div className="example-hand">{parseHand('m123p123s123789z11').map((p, i) => <Tile key={i} code={p} small />)}</div><p>通常用四组面子加一个对子和牌。面子可以是连续三张同花色的顺子，或三张相同牌的刻子。七对子和国士无双是特殊牌型。</p><h3>完成牌型，还需要有役</h3><p>宝牌增加番数，但宝牌本身不算役。门前指没有吃、碰或明杠；暗杠不破坏门前。吃只能吃上家的弃牌，碰和明杠可来自其他人。</p><h3>立直与振听</h3><p>门前听牌且满足点数、余牌条件时可以支付 1000 点立直。立直后通常必须摸切。若自己的弃牌包含当前听牌，不能荣和；放弃可和的牌也可能进入临时振听，立直后放弃则持续到本局结束。振听仍可自摸。</p><h3>和牌</h3><p>引擎判断可以和牌时，提供自摸或荣和。无效请求会被拒绝，不公开手牌或扣分。</p><h3>没有时间限制</h3><p>弃牌后各座位提交响应或跳过，收齐后统一处理。聊天随时可用，私聊及教练内容不进入公共上下文。</p></>}
    {tab === 'actions' && <><h3>吃、碰、杠</h3><p>吃只能取上家的弃牌组成顺子；碰可取任意一家的弃牌组成刻子；杠由四张同牌组成，分暗杠、明杠和加杠。响应阶段没有倒计时，每个座位明确选择动作或跳过，程序收齐后处理。</p><p>荣和优先于副露，碰和杠优先于吃。当前房间最多允许 {state.rules.multipleRon} 人同时荣和。吃碰后必须弃牌；程序禁止食替。</p><h3>立直与和牌</h3><p>门前听牌、点数和余牌满足条件时可立直，支付 1000 点。立直后通常只能摸切。荣和必须有当前弃牌或可抢的加杠牌；自摸必须在自己摸牌后。振听时不能荣和。</p><h3>终止对局</h3><p>桌心菜单可终止整桌对战：取消模型任务，点数重置，不结算排名或存入历史对战。</p><h3>特殊流局</h3><p>首巡满足条件可宣告九种九牌。荒牌流局、四风连打、四家立直、四杠散了与三家荣和的处理按引擎和当前房规执行。</p></>}
    {tab === 'yaku' && <><input className="search-input" placeholder="搜索役种、番数或门前…" value={search} onChange={e => setSearch(e.target.value)} /><div className="yaku-grid">{YAKU.filter(y => y.join(' ').includes(search)).map(([name, han, desc, example]) => <article key={name} className="yaku-card"><div><h3>{name}</h3><span>{han}</span></div><p>{desc}</p>{example && <div className="example-hand">{parseHand(example).map((p, i) => <Tile key={i} code={p} small />)}</div>}</article>)}</div><p className="form-note">牌例只示意结构；实际番符还取决于和牌张、门前状态、自风及场风。特殊役满与复合以引擎为准。</p></>}
    {tab === 'scoring' && <><h3>番数与符数</h3><p>先判断役，再计算宝牌和符，选择得点最高的合法拆分。基本点为 20 符；门前荣和加 10 符，自摸通常加 2 符，刻子、杠子、役牌雀头及听牌形状会加符，最终通常向上取整到十位。七对子固定 25 符；平和自摸为 20 符。</p><table className="score-table"><thead><tr><th>档位</th><th>常见条件</th><th>闲家荣和</th><th>庄家荣和</th></tr></thead><tbody>{[['满贯', '5 番 / 达到满贯基本点', 8000, 12000], ['跳满', '6–7 番', 12000, 18000], ['倍满', '8–10 番', 16000, 24000], ['三倍满', '11–12 番', 24000, 36000], ['役满', '役满役 / 13 番以上数役满', 32000, 48000]].map(row => <tr key={row[0]}>{row.map((v, i) => <td key={i}>{typeof v === 'number' ? v.toLocaleString() : v}</td>)}</tr>)}</tbody></table><p>荣和由放铳者支付；自摸由其他三家支付。每本场增加总计 300 点，供托归和牌者。多人荣和和役满责任支付由引擎处理。</p><h3>流局与连庄</h3><p>荒牌流局中，听牌者与未听牌者分配总计 3000 点罚符。庄家和牌或荒牌流局听牌可连庄。四风连打、四家立直、四杠散了、九种九牌等按引擎配置处理。</p></>}
    {tab === 'current' && <><h3>房间设置</h3><p>{matchLabel(state.rules)} · 赤五{state.rules.redFives ? '开启' : '关闭'} · 食断{state.rules.openTanyao ? '开启' : '关闭'} · 最多 {state.rules.multipleRon} 人同时荣和。</p><p>以下是完整房规；模型提示词使用精简版本。</p><pre className="english-rules">{state.englishRules}</pre></>}
    <div className="source-note">日麻规则引擎：<a href="https://github.com/kobalab/majiang-core" target="_blank" rel="noreferrer">majiang-core（MIT）</a> · 牌面：<a href="https://github.com/FluffyStuff/riichi-mahjong-tiles" target="_blank" rel="noreferrer">FluffyStuff（公有领域）</a> · <a href="https://www.worldriichi.org/wrc-rules" target="_blank" rel="noreferrer">WRC 规则参考</a><br />本项目支持自定义局数，不是 WRC 官方预设。</div>
    </div></>;
}
export function ContextPanel({ state, run, onReplay }) {
  const coachEnabled = state.seats[0].type === 'human';
  const [tab, setTab] = useState('public');
  useEffect(() => { if (!coachEnabled && tab === 'coach') setTab('public'); }, [coachEnabled, tab]);
  const events = tab === 'public' ? state.publicEvents : tab === 'coach' ? state.coachEvents || [] : tab === 'all-private' ? state.observerPrivateEvents || [] : state.privateEvents;
  return <><div className="modal-heading"><small>CONTEXT POOLS</small><h2>上下文池</h2><p>公共信息共享，私有信息按座位隔离。时间为距整场对局开始的累计耗时（hh:mm:ss）。</p></div><div className="context-stats"><div><small>牌局版本</small><b>{state.version}</b></div><div><small>最新事件</small><b>#{state.eventId}</b></div><div><small>等待响应</small><b>{state.waiting.length ? state.waiting.map(i => state.seats[i].name).join('、') : '—'}</b></div></div><div className="tabs panel-tabs"><button className={tab === 'public' ? 'chosen' : ''} onClick={() => setTab('public')}>公共上下文</button><button className={tab === 'private' ? 'chosen' : ''} onClick={() => setTab('private')}>我的私有上下文</button><button hidden={!coachEnabled} className={tab === 'coach' ? 'chosen' : ''} onClick={() => setTab('coach')}>教练私有上下文</button><button className={tab === 'all-private' ? 'chosen' : ''} onClick={() => setTab('all-private')}>全桌私有记录</button><button className={tab === 'process' ? 'chosen' : ''} onClick={() => setTab('process')}>进程状态</button></div>
    <div className="context-content">{tab === 'process' ? <div className="process-list">{Object.entries(state.agentStatus).length ? Object.entries(state.agentStatus).map(([key, s]) => <article className="process-card" key={key}><div><strong>{key}</strong><small>PID {s.pid || '—'} · {s.state}</small><ErrorDetails error={s.error} /></div><button className="secondary" onClick={() => run(() => api('retry', { seat: Number(key.split(':')[1]), role: key.split(':')[0] }))}>重启 / 重试</button></article>) : <p>首次决策或聊天时启动对应子进程。</p>}</div> : <><p className="form-note">{state.replay ? '显示截至当前回放位置的全部事件。' : tab === 'public' ? '此池不包含暗牌、牌墙或教练私聊。显示最近 160 条事件。' : tab === 'coach' ? '教练私聊和记忆，仅你和绑定教练可见。显示最近 100 条事件。' : tab === 'all-private' ? '包含私聊和各角色记忆，仅本机玩家可查看全桌记录，不发送给其他模型。' : '展示你的座位私聊和记忆。显示最近 100 条事件。'}</p>{events.slice().reverse().map(e => <details className="context-event" key={e.id}><summary><span>#{e.id}</span><strong>{e.type === 'chat' ? `${state.seats[e.data.seat]?.name} → ${state.seats[Number(e.data.target?.slice(5))]?.name || e.data.target}` : e.type === 'memory' ? `${state.seats[e.data.seat]?.name || '教练'} · 记忆更新` : e.type}</strong><time title={e.at ? new Date(e.at).toLocaleString() : undefined}>{eventTime(e, state.matchStartedAt)}</time></summary><pre>{JSON.stringify(e.data, null, 2)}</pre></details>)}</>}
      <div className="modal-actions"><span>完整上下文与存档保留在本机</span><button className="primary" onClick={() => onReplay()}>历史对战</button>{!state.replay && state.replayId && <><button className="secondary" onClick={() => onReplay(state.replayId)}>回看本次对战</button><button className="secondary" onClick={async () => { const data = await run(() => api('replay')); if (data) download(`riichi-replay-${Date.now()}.json`, data); }}>导出牌局记录</button></>}</div>
    </div></>;
}
